-- 漂浮字符
ttg.char("default", "0", "lik_word_0", 1.9)
ttg.char("default", "1", "lik_word_1", 1.8)
ttg.char("default", "2", "lik_word_2", 1.8)
ttg.char("default", "3", "lik_word_3", 1.8)
ttg.char("default", "4", "lik_word_4", 1.8)
ttg.char("default", "5", "lik_word_5", 1.8)
ttg.char("default", "6", "lik_word_6", 1.8)
ttg.char("default", "7", "lik_word_7", 1.8)
ttg.char("default", "8", "lik_word_8", 1.8)
ttg.char("default", "9", "lik_word_9", 1.8)
ttg.char("default", "+", "lik_word_+", 1.7)
ttg.char("default", "-", "lik_word_-", 1.7)
ttg.char("default", "C", "lik_word_crit", 2.5)